name: Process content

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      # Configure pandoc installation cache
      - name: Cache pandoc installation
        id: cache-pandoc-installation
        uses: actions/cache@v3
        with:
          path: "~/pandoc-installation-cache"
          key: ${{ runner.os }}-pandoc-cache-2022-10-13-02
      # Install pandoc from scratch
      - name: Install pandoc from scratch
        if: steps.cache-pandoc-installation.outputs.cache-hit != 'true'
        run: |
          mkdir ~/pandoc-installation-cache
          sudo apt-get update
          sudo apt-get install pandoc -y
          sudo dpkg -L pandoc | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/pandoc-installation-cache/
          sudo dpkg -L pandoc-data | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/pandoc-installation-cache/
          sudo apt-get install texlive-xetex -y
          sudo dpkg -L texlive-xetex | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/pandoc-installation-cache/
          sudo dpkg -L libharfbuzz0b | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/pandoc-installation-cache/

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure git author
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      
      - name: Configure pandoc installation cache
        id: cache-pandoc-installation
        uses: actions/cache@v3
        with:
          path: "~/pandoc-installation-cache"
          key: ${{ runner.os }}-pandoc-cache-2022-10-13-02

      - name: Install pandoc from cache
        if: steps.cache-pandoc-installation.outputs.cache-hit == 'true'
        run: |
          sudo cp --verbose --force --recursive ~/pandoc-installation-cache/* /

      # Runs a single command using the runners shell
      - name: Convert content and commit
        run: ./commit.sh
