name: Process content

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure git author
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-xetex -y

      - name: Convert content and commit
        run: ./commit.sh
